cluster:
  mkdir -p logs/slurm &&
  sbatch
    --account={resources.account}
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem="{resources.mem_gb}G"
    --job-name=smk-{rule}-{wildcards}
    --time={resources.time}
    --output=logs/slurm/{rule}-{wildcards}-%j.out
    --parsable
default-resources:
  - account="2023-bjp-sandbox"
  - partition=compute,hugemem
  - time=480
  - mem_gb=24
restart-times: 3
latency-wait: 6000
jobs: 150
max-jobs-per-second: 0.5
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
use-singularity: True
reason: True
conda-frontend: conda
rerun-trigger: mtime
cluster-status: workflow/scripts/status.py
cluster-cancel: scancel